// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjC8ebhHaoB70OafNDyD5yJjMC-dY7P6c',
    appId: '1:856785521982:web:51332db66f2b9505c4b06f',
    messagingSenderId: '856785521982',
    projectId: 'quick-deliver-2da14',
    authDomain: 'quick-deliver-2da14.firebaseapp.com',
    storageBucket: 'quick-deliver-2da14.firebasestorage.app',
    measurementId: 'G-7WKZB9R21J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbbDmFSmGFzaXsvGwKa8ZchN-UroOv4fI',
    appId: '1:856785521982:android:f3c86f0dd34ab251c4b06f',
    messagingSenderId: '856785521982',
    projectId: 'quick-deliver-2da14',
    storageBucket: 'quick-deliver-2da14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ8yxlgqVR1msKVzWrs8C_kfmS9SAu-3M',
    appId: '1:856785521982:ios:66236cb330d9a74ec4b06f',
    messagingSenderId: '856785521982',
    projectId: 'quick-deliver-2da14',
    storageBucket: 'quick-deliver-2da14.firebasestorage.app',
    iosBundleId: 'com.example.quickDeliver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ8yxlgqVR1msKVzWrs8C_kfmS9SAu-3M',
    appId: '1:856785521982:ios:66236cb330d9a74ec4b06f',
    messagingSenderId: '856785521982',
    projectId: 'quick-deliver-2da14',
    storageBucket: 'quick-deliver-2da14.firebasestorage.app',
    iosBundleId: 'com.example.quickDeliver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjC8ebhHaoB70OafNDyD5yJjMC-dY7P6c',
    appId: '1:856785521982:web:443887ad6936bbf4c4b06f',
    messagingSenderId: '856785521982',
    projectId: 'quick-deliver-2da14',
    authDomain: 'quick-deliver-2da14.firebaseapp.com',
    storageBucket: 'quick-deliver-2da14.firebasestorage.app',
    measurementId: 'G-YTX517MJMM',
  );
}
